### ISSUE TITLE
点击登录会报错

### ISSUE THREAD

**Issue by chennadar** [largezhou/lz-shop#25]
`生产环境` 是没问题的

但是 `开发环境` 开启代理后，点击登录会报错
![code](https://user-images.githubusercontent.com/43457341/205649196-76a5d93a-acf2-4f5d-a990-9f8030b8d5b4.png)

这个 `messages` 是 未定义的，是不是应该写成 `message`
![code2](https://user-images.githubusercontent.com/43457341/205651347-ae6ec8dc-256e-4536-833d-752feaf7f8a1.png)

**Comment by largezhou** [comment]
可能是 devServer 的问题，这个 messages 是通过 http://your-host/messages.js 加载的，文件是 `public/messages.js`，内容很简单。

你可以暂时直接把这部分内容，写到 js 的全局变量里。

我有空会处理一下

**Comment by chennadar** [comment]
> 可能是 devServer 的问题，这个 messages 是通过 http://your-host/messages.js 加载的，文件是 `public/messages.js`，内容很简单。
> 
> 你可以暂时直接把这部分内容，写到 js 的全局变量里。
> 
> 我有空会处理一下

感谢解答！问题解决了。确实，属于前端的代码放在前端工程项目里才合理
